version: '3.5'

services:
  web:
    image: "rodrigoom/magicreator:1.0"
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:4.0
    hostname: "mongodb"
    container_name: "magicreator_mongodb"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: magicreator

